### ISSUE TITLE
env variables

### ISSUE THREAD

**Issue by johnykov** [aleross/angular-segment-analytics#6]
Hi, I'm happy user of you plugin, I love it! It helps a lot;)

What do you use (or how) to set environment variables? I noticed you use in code `$rootScope.isProduction` what looks nice a clean. Is some kind of plugin to grunt/gulp?

**Comment by aleross** [comment]
I'm glad you like it!

In projects I've worked on we either use different domains (either TLDs like .com/.io etc, or subdomains) or cookies to control the environment with a service for keeping track of it. For example, if the application is loaded on staging.company.com, then we'd have an `Environment.js` service that might have a `get()` method on it which knows that the environment is staging because it's being run on the staging subdomain. We also have methods like `Environment.isProduction()` that return a boolean because we only have 3 fixed environments (prod, staging, dev).

If you're creating different builds for different environments and storing the environment in a static JSON, JS, or HTML file, then you could use any of the several grunt-replace type of tasks in tandem with grunt-prompt or something to select the environment you're building for.

I hope this helps give you some ideas, happy to answer any other questions.

**Comment by johnykov** [comment]
Thanks for inspiration and that verbose answer, I'm going to figure out
best configuration ;)
09.02.2016 7:35 PM "Alex Ross" notifications@github.com napisał(a):
