### ISSUE TITLE
Does this support intercomm's support feature?

### ISSUE THREAD

**Issue by jmgamboa** [aleross/angular-segment-analytics#9]
When calling the identify function, segment's integration with intercom's support, will load the chat widget.  However, while my identify and page functions are firing, I still see no chat widget.

**Comment by jmgamboa** [comment]
basically I'm getting this error. trying to call identify and page
"Not calling method, condition returned false."

**Comment by jmgamboa** [comment]
found it here where the error comes from https://github.com/aleross/angular-segment-analytics/blob/4de3aa351c369e1e45fdec88dfd8614c06c009e8/segment.js#L153, and here

**Comment by m0rganic** [comment]
I've got the exact same problem. Are there any additional steps required for intercom integration?

**Comment by m0rganic** [comment]
I  am however receiving a HTTP 200 from the ping to intercom's api

<img width="582" alt="screen shot 2016-03-04 at 8 41 50 pm" src="https://cloud.githubusercontent.com/assets/525275/13545204/8f11031c-e249-11e5-94b7-66d8e1130fa7.png">

**Comment by m0rganic** [comment]
Digging deeper into the intercom product documentation now it looks like the live chat is potentially a separate product from the customer tracking that segment has integrated. But it's unclear to me at this point whether it requires a separate sdk to get live chat going.

**Comment by jmgamboa** [comment]
@m0rganic yes. intercom support(chat widget) is a separate feature, they provide.

**Comment by aleross** [comment]
I haven't had an issue with the chat widget + Segment + this module before (if you mean the bottom-right (?) clickable button). @m0rganic I don't believe I needed a separate SDK. I would check your Intercom settings and CSS styling.

You could also try isolating the chat behavior by loading the Segment JS SDK on an empty index.html page and calling identify to see if the chat triggers. Let me know if it does, which would point to a problem with this module integration.

@jmgamboa the `Not calling method, condition returned false` shows when you have a `segment.setCondition(function () { // return things });` function set to conditionally stop calls from being made. Could you share more of your segment setup code so that I can look closer?

**Comment by m0rganic** [comment]
I got intercom chat working and you're right it had nothing to do with the
error - no additional ask required.

I did discover, however that the setCondition method mentioned above wrecks
havoc on my app after I grunt uglify my code. I removed that call in my
config section of my app and my problems went away.

**Comment by aleross** [comment]
Glad Intercom is working.

@m0rganic that'll likely be because the `setCondition` function has dependency injection so that you can specify things like `function ($rootScope) {}` as a parameter and have it available. You'll need to use explicit annotations or a grunt plugin like `ngAnnotate` with uglify, like you do with controllers and other dependency-injected functions.

Example:

``` js
segment.setCondition(['$rootScope', function($rootScope) {
    return $rootScope.isProduction;
});

Looking at the code though, I think this module may require that the condition is a callback function. So you could also look into whether Uglify has a way to skip certain lines. If this is a problem you could open another issue and I'll see if I can get to it.
```
